[package]
name = "organizer"
version = "0.1.0"
authors = ["Gian12315 <giancarlo.cytro@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.18"
glob = "0.3.0"